# Generated by Django 2.2.7 on 2019-11-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_truefalsequestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrueFalseQuestions',
            new_name='TrueFalseQuestion',
        ),
    ]
